# Generated by Django 4.2.2 on 2023-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
